/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutModal: typeof import('./src/components/modals/AboutModal.vue')['default']
    ChangelogDrawer: typeof import('./src/components/drawers/ChangelogDrawer.vue')['default']
    FeedbackModal: typeof import('./src/components/modals/FeedbackModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TBadge: typeof import('tdesign-vue-next')['Badge']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TCol: typeof import('tdesign-vue-next')['Col']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    THeader: typeof import('tdesign-vue-next')['Header']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLink: typeof import('tdesign-vue-next')['Link']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TRow: typeof import('tdesign-vue-next')['Row']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTag: typeof import('tdesign-vue-next')['Tag']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}

// For TSX support
declare global {
  const AboutModal: typeof import('./src/components/modals/AboutModal.vue')['default']
  const ChangelogDrawer: typeof import('./src/components/drawers/ChangelogDrawer.vue')['default']
  const FeedbackModal: typeof import('./src/components/modals/FeedbackModal.vue')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
  const IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
  const IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
  const IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
  const IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TAside: typeof import('tdesign-vue-next')['Aside']
  const TAvatar: typeof import('tdesign-vue-next')['Avatar']
  const TBadge: typeof import('tdesign-vue-next')['Badge']
  const TButton: typeof import('tdesign-vue-next')['Button']
  const TCard: typeof import('tdesign-vue-next')['Card']
  const TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
  const TCol: typeof import('tdesign-vue-next')['Col']
  const TContent: typeof import('tdesign-vue-next')['Content']
  const TDropdown: typeof import('tdesign-vue-next')['Dropdown']
  const TFooter: typeof import('tdesign-vue-next')['Footer']
  const THeader: typeof import('tdesign-vue-next')['Header']
  const TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
  const TIcon: typeof import('tdesign-vue-next')['Icon']
  const TInput: typeof import('tdesign-vue-next')['Input']
  const TLayout: typeof import('tdesign-vue-next')['Layout']
  const TLink: typeof import('tdesign-vue-next')['Link']
  const TList: typeof import('tdesign-vue-next')['List']
  const TListItem: typeof import('tdesign-vue-next')['ListItem']
  const TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
  const TMenu: typeof import('tdesign-vue-next')['Menu']
  const TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
  const TPopup: typeof import('tdesign-vue-next')['Popup']
  const TRow: typeof import('tdesign-vue-next')['Row']
  const TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
  const TTabs: typeof import('tdesign-vue-next')['Tabs']
  const TTag: typeof import('tdesign-vue-next')['Tag']
  const WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
}